module.exports = {
  sidebar: [
    {
      className: "nav-item",
      activeClass: "active",
      to: "profile",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -40,
      text: "Profile",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "skills",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -40,
      text: "Skills",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "experience",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -40,
      text: "Experience",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "projects",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -40,
      text: "Projects",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "contact",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -40,
      text: "Contact",
    },
  ],
  navbar: [
    {
      className: "nav-item",
      activeClass: "active",
      to: "profile",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -100,
      text: "Profile",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "skills",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -100,
      text: "Skills",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "experience",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -100,
      text: "Experience",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "projects",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -100,
      text: "Projects",
    },
    {
      className: "nav-item",
      activeClass: "active",
      to: "contact",
      spy: true,
      smooth: true,
      duration: 400,
      offset: -100,
      text: "Contact",
    },
  ],  
};
